'use server';

/**
 * @fileOverview This file defines a Genkit flow for answering customer questions about printing.
 *
 * The flow takes a question as input and returns an answer generated by the Gemini API.
 *
 * @Exported Members:
 *   - `answerPrintingQuestion`:  The function to call to answer a question.
 *   - `AnswerPrintingQuestionInput`: The input type for the `answerPrintingQuestion` function.
 *   - `AnswerPrintingQuestionOutput`: The output type for the `answerPrintingQuestion` function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnswerPrintingQuestionInputSchema = z.object({
  question: z.string().describe('The question to answer about printing.'),
});
export type AnswerPrintingQuestionInput = z.infer<typeof AnswerPrintingQuestionInputSchema>;

const AnswerPrintingQuestionOutputSchema = z.object({
  answer: z.string().describe('The answer to the question.'),
});
export type AnswerPrintingQuestionOutput = z.infer<typeof AnswerPrintingQuestionOutputSchema>;

export async function answerPrintingQuestion(input: AnswerPrintingQuestionInput): Promise<AnswerPrintingQuestionOutput> {
  return answerPrintingQuestionFlow(input);
}

const prompt = ai.definePrompt({
  name: 'answerPrintingQuestionPrompt',
  input: {schema: AnswerPrintingQuestionInputSchema},
  output: {schema: AnswerPrintingQuestionOutputSchema},
  prompt: `You are a helpful printing assistant.  Answer the following question about printing materials, finishes, and pricing:

  Question: {{{question}}}
  `,
});

const answerPrintingQuestionFlow = ai.defineFlow(
  {
    name: 'answerPrintingQuestionFlow',
    inputSchema: AnswerPrintingQuestionInputSchema,
    outputSchema: AnswerPrintingQuestionOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
